[package]
name = "jam"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.8"
bevy_egui = "0.15"
rand = "0.8.5"
asset_struct = { path = "./crates/asset_struct" }
global_state = { path = "./crates/global_state" }
